#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : ark
Version  : 19.04.0
Release  : 24
URL      : https://download.kde.org/stable/applications/19.04.0/src/ark-19.04.0.tar.xz
Source0  : https://download.kde.org/stable/applications/19.04.0/src/ark-19.04.0.tar.xz
Source99 : https://download.kde.org/stable/applications/19.04.0/src/ark-19.04.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1 LGPL-3.0
Requires: ark-bin = %{version}-%{release}
Requires: ark-data = %{version}-%{release}
Requires: ark-lib = %{version}-%{release}
Requires: ark-license = %{version}-%{release}
Requires: ark-locales = %{version}-%{release}
Requires: ark-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : bzip2-dev
BuildRequires : extra-cmake-modules shared-mime-info
BuildRequires : libarchive-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(libzip)
BuildRequires : xz-dev
BuildRequires : zlib-dev

%description
What is it
----------
Ark is a graphical file compression/decompression utility with support for multiple formats,
including tar, gzip, bzip2, rar and zip, as well as CD-ROM images.
Ark can be used to browse, extract, create, and modify archives.

%package bin
Summary: bin components for the ark package.
Group: Binaries
Requires: ark-data = %{version}-%{release}
Requires: ark-license = %{version}-%{release}

%description bin
bin components for the ark package.


%package data
Summary: data components for the ark package.
Group: Data

%description data
data components for the ark package.


%package doc
Summary: doc components for the ark package.
Group: Documentation
Requires: ark-man = %{version}-%{release}

%description doc
doc components for the ark package.


%package lib
Summary: lib components for the ark package.
Group: Libraries
Requires: ark-data = %{version}-%{release}
Requires: ark-license = %{version}-%{release}

%description lib
lib components for the ark package.


%package license
Summary: license components for the ark package.
Group: Default

%description license
license components for the ark package.


%package locales
Summary: locales components for the ark package.
Group: Default

%description locales
locales components for the ark package.


%package man
Summary: man components for the ark package.
Group: Default

%description man
man components for the ark package.


%prep
%setup -q -n ark-19.04.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1556994415
mkdir -p clr-build
pushd clr-build
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1556994415
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ark
cp COPYING %{buildroot}/usr/share/package-licenses/ark/COPYING
cp COPYING.icons %{buildroot}/usr/share/package-licenses/ark/COPYING.icons
pushd clr-build
%make_install
popd
%find_lang ark

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ark

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.ark.desktop
/usr/share/config.kcfg/ark.kcfg
/usr/share/icons/hicolor/128x128/apps/ark.png
/usr/share/icons/hicolor/48x48/apps/ark.png
/usr/share/icons/hicolor/64x64/apps/ark.png
/usr/share/icons/hicolor/scalable/apps/ark.svgz
/usr/share/kservices5/ark_part.desktop
/usr/share/kservicetypes5/kerfufflePlugin.desktop
/usr/share/kxmlgui5/ark/ark_viewer.rc
/usr/share/metainfo/org.kde.ark.appdata.xml
/usr/share/mime-packages/kerfuffle.xml
/usr/share/xdg/ark.categories

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/de/ark/ark-mainwindow.png
/usr/share/doc/HTML/de/ark/index.cache.bz2
/usr/share/doc/HTML/de/ark/index.docbook
/usr/share/doc/HTML/en/ark/ark-comment.png
/usr/share/doc/HTML/en/ark/ark-mainwindow.png
/usr/share/doc/HTML/en/ark/create-archive.png
/usr/share/doc/HTML/en/ark/create-protected-archive.png
/usr/share/doc/HTML/en/ark/extract-dialog.png
/usr/share/doc/HTML/en/ark/index.cache.bz2
/usr/share/doc/HTML/en/ark/index.docbook
/usr/share/doc/HTML/es/ark/index.cache.bz2
/usr/share/doc/HTML/es/ark/index.docbook
/usr/share/doc/HTML/et/ark/index.cache.bz2
/usr/share/doc/HTML/et/ark/index.docbook
/usr/share/doc/HTML/fr/ark/ark-mainwindow.png
/usr/share/doc/HTML/fr/ark/index.cache.bz2
/usr/share/doc/HTML/fr/ark/index.docbook
/usr/share/doc/HTML/gl/ark/index.cache.bz2
/usr/share/doc/HTML/gl/ark/index.docbook
/usr/share/doc/HTML/it/ark/index.cache.bz2
/usr/share/doc/HTML/it/ark/index.docbook
/usr/share/doc/HTML/nl/ark/index.cache.bz2
/usr/share/doc/HTML/nl/ark/index.docbook
/usr/share/doc/HTML/pl/ark/index.cache.bz2
/usr/share/doc/HTML/pl/ark/index.docbook
/usr/share/doc/HTML/pt/ark/index.cache.bz2
/usr/share/doc/HTML/pt/ark/index.docbook
/usr/share/doc/HTML/pt_BR/ark/ark-mainwindow.png
/usr/share/doc/HTML/pt_BR/ark/create-protected-archive.png
/usr/share/doc/HTML/pt_BR/ark/index.cache.bz2
/usr/share/doc/HTML/pt_BR/ark/index.docbook
/usr/share/doc/HTML/ru/ark/index.cache.bz2
/usr/share/doc/HTML/ru/ark/index.docbook
/usr/share/doc/HTML/sr/ark/index.cache.bz2
/usr/share/doc/HTML/sr/ark/index.docbook
/usr/share/doc/HTML/sv/ark/index.cache.bz2
/usr/share/doc/HTML/sv/ark/index.docbook
/usr/share/doc/HTML/uk/ark/ark-comment.png
/usr/share/doc/HTML/uk/ark/ark-mainwindow.png
/usr/share/doc/HTML/uk/ark/create-archive.png
/usr/share/doc/HTML/uk/ark/create-protected-archive.png
/usr/share/doc/HTML/uk/ark/extract-dialog.png
/usr/share/doc/HTML/uk/ark/index.cache.bz2
/usr/share/doc/HTML/uk/ark/index.docbook

%files lib
%defattr(-,root,root,-)
/usr/lib64/libkerfuffle.so.19
/usr/lib64/libkerfuffle.so.19.4.0
/usr/lib64/qt5/plugins/arkpart.so
/usr/lib64/qt5/plugins/kerfuffle/kerfuffle_cli7z.so
/usr/lib64/qt5/plugins/kerfuffle/kerfuffle_clirar.so
/usr/lib64/qt5/plugins/kerfuffle/kerfuffle_cliunarchiver.so
/usr/lib64/qt5/plugins/kerfuffle/kerfuffle_clizip.so
/usr/lib64/qt5/plugins/kerfuffle/kerfuffle_libarchive.so
/usr/lib64/qt5/plugins/kerfuffle/kerfuffle_libarchive_readonly.so
/usr/lib64/qt5/plugins/kerfuffle/kerfuffle_libbz2.so
/usr/lib64/qt5/plugins/kerfuffle/kerfuffle_libgz.so
/usr/lib64/qt5/plugins/kerfuffle/kerfuffle_libxz.so
/usr/lib64/qt5/plugins/kerfuffle/kerfuffle_libzip.so
/usr/lib64/qt5/plugins/kf5/kfileitemaction/compressfileitemaction.so
/usr/lib64/qt5/plugins/kf5/kfileitemaction/extractfileitemaction.so
/usr/lib64/qt5/plugins/kf5/kio_dnd/extracthere.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ark/COPYING
/usr/share/package-licenses/ark/COPYING.icons

%files man
%defattr(0644,root,root,0755)
/usr/share/man/ca/man1/ark.1
/usr/share/man/de/man1/ark.1
/usr/share/man/es/man1/ark.1
/usr/share/man/fr/man1/ark.1
/usr/share/man/gl/man1/ark.1
/usr/share/man/it/man1/ark.1
/usr/share/man/man1/ark.1
/usr/share/man/nl/man1/ark.1
/usr/share/man/pt/man1/ark.1
/usr/share/man/pt_BR/man1/ark.1
/usr/share/man/sr/man1/ark.1
/usr/share/man/sv/man1/ark.1
/usr/share/man/uk/man1/ark.1

%files locales -f ark.lang
%defattr(-,root,root,-)

